export const Courses_list = [{
        id: 1,
        title: "Algorithmic Toolbox,University of California San Diego.",
        place: "Coursera",
        file_name: "Coursera_Algo_California_san_diago",
        url: "https://drive.google.com/file/d/14rofaQ5vpB3kTL5kmYvsTxVVshQmzAzL/view?usp=sharing",
    },
    {
        id: 2,
        title: "VMware Students Workshop at DELL Technologies",
        place: "Cairo, Egypt",
        file_name: "dell_Certificate",
        url: "https://drive.google.com/file/d/1-CyFQmIrezEuVPqOFgCXLaxm5raEtmYK/view?usp=sharing",
    },
    {
        id: 3,
        title: "API Design and Fundamentals of Google Cloud’s Apigee API Platform.",
        place: "Coursera",
        file_name: "apigee_design",
        url: "https://drive.google.com/file/d/18FrkITLl4Gug9pd4w9dzW6Uq2_n2P-qW/view?usp=sharing",
    },
    {
        id: 4,
        title: "API Security on Google Cloud’s Apigee API Platform.",
        place: "Coursera",
        file_name: "apigee_security",
        url: "https://drive.google.com/file/d/1Kr_4Vmi83CUT_I9Cb9PxURPB0aB1bHXM/view?usp=sharing",
    },
    {
        id: 5,
        title: "API Development on Google Cloud’s Apigee API Platform.",
        place: "Coursera",
        file_name: "apigee_dev",
        url: "https://drive.google.com/file/d/11q_qAnYXwXdv2XU1Mr3nC-Qq_pTVc4RY/view?usp=sharing",
    },
    {
        id: 6,
        title: "ROS (Robot Operating System) summer school from FH Aachen",
        place: "Aachen, Germany",
        file_name: "ROS_Certificate",
        url: "https://drive.google.com/file/d/1k2UyG1NPKKSpvfxCBwkpMYG_x2TmiS1S/view",
    },
];