export const skills = [{
        id: 1,
        name: "Java",
        level: 90,
        level_name: "intermediat",
    },
    {
        id: 2,
        name: "C++",
        level: 60,
        level_name: "intermediat",
    },
    {
        id: 3,
        name: "python",
        level: 80,
        level_name: "intermediat",
    },
    {
        id: 4,
        name: "JavaScript",
        level: 70,
        level_name: "intermediat",
    },
    {
        id: 5,
        name: "REACT.JS",
        level: 60,
        level_name: "intermediat",
    },
    {
        id: 6,
        name: "Node.JS",
        level: 40,
        level_name: "intermediat",
    },
    {
        id: 7,
        name: "php",
        level: 60,
        level_name: "intermediat",
    },
];

export const ProjectsData = [{
        id: 1,
        title: "Coloring-Machine-from-SVG_image-using-marlin",
        image: "https://lh3.googleusercontent.com/d/1_sIl8F6xOxA9ZNVLjrLoCya8CReeZXpp=s220?authuser=0",
        discription: "this project take any SVG image with size 300x300 mm and convert this image to Gcode. the Gcode then you can take the output file and send it serially to marlin firmware using pronterface",
        link: "https://github.com/RimonAdel/Coloring-Machine-from-SVG_image-using-marlin",
    },
    {
        id: 2,
        title: "Circus-OF-Plates",
        image: "https://lh3.googleusercontent.com/d/1pyu0ot433NH7f4ZrsCV-wsH3Ub2jOasN=s220?authuser=0",
        discription: "2D game implementing 10 Design Patterns•The player select levels of hardness from three levels determining the speed of the game and probability of bombs presence in the game",
        link: "https://github.com/RimonAdel/Circus-OF-Plates",
    },
    {
        id: 3,
        title: "stereo-Matching",
        image: "https://lh3.googleusercontent.com/d/1Kwn0Psj37yfcyauXBvTYebOYXrJJ19R-=s220?authuser=0",
        discription: "implements and tests some simple stereo matching algorithms discussed in computer vision for undergradates class. In each case the script will take two images Il and Ir (a left and a right image) and compute the horizontal disparity (ie., shift) of pixels along each scanline. This is the so-called baseline stereo case, where the images are taken with a forward-facing camera, and the translation between cameras is along the horizontal axis.",
        link: "https://github.com/RimonAdel/stereo-Matching",
    },
    {
        id: 4,
        title: "8 Puzzle Solver",
        image: "https://drive.google.com/thumbnail?id=1hrTlx2npik1ygILE1plL8CaGw8xnP4KT",
        discription: "solve the 8-Puzzle game using different search techniques like : Breadth Frist Serach, Depth Frist Serach and A*",
        link: "https://github.com/RimonAdel/8-Puzzle",
    },
    {
        id: 5,
        title: "IOT-project-using-ESP8266",
        image: "https://drive.google.com/thumbnail?id=1FKsSE3notWnV6xxAsvUVek01Rd8_tY0d",
        discription: "About using java to make 2D game implementing 10 Design Patterns•The player select levels of hardness from three levels determining the speed of the game and probability of bombs presence in the game",
        link: "https://github.com/RimonAdel/Circus-OF-Plates",
    },
    {
        id: 6,
        title: "Human Measurment System",
        image: "https://drive.google.com/thumbnail?id=1KyNMcuJKakQd1VMynxSOKnUkS8BJWVB8",
        discription: "Extracting the human body measurements such as hip, waist, chest and shoulders using machine learning and computer vision ",
        link: "https://github.com/RimonAdel/Human-Measurment-System",
    },
];

export const workExperience = [{
        id: 1,
        jobTitle: "Software Engineer",
        company: "Ejada",
        startDate: "2020-8-16",
        endDate: "",
        details: "backend developer",
        country: "Egypt",
        type: "Full-Time"
    },
    {
        id: 2,
        jobTitle: "Software Engineer",
        company: "Xcode Systems",
        startDate: "2018-8-1",
        endDate: "2018-10-1",
        details: "android mobile developer",
        country: "Egypt",
        type: "inten"
    },
    {
        id: 3,
        jobTitle: "Robotics Software Engineer",
        company: "mind cloud (Collage Team)",
        startDate: "2017-6-1",
        endDate: "2019-6-1",
        details: "python and c++ developer at my college competitions team",
        country: "Egypt",
        type: "part-time"
    },
]

export const Courses_list = [{
        id: 1,
        title: "Algorithmic Toolbox, University of California San Diego.",
        place: "Coursera",
        file_name: "Coursera_Algo_California_san_diago",
        url: "https://drive.google.com/file/d/14rofaQ5vpB3kTL5kmYvsTxVVshQmzAzL/view?usp=sharing",
    },
    {
        id: 2,
        title: "Data Structures, University of California San Diego.",
        place: "Coursera",
        file_name: "Coursera_DS_California_san_diago",
        url: "https://drive.google.com/file/d/14rofaQ5vpB3kTL5kmYvsTxVVshQmzAzL/view?usp=sharing",
    },
    {
        id: 3,
        title: "VMware Students Workshop at DELL Technologies",
        place: "Cairo, Egypt",
        file_name: "dell_Certificate",
        url: "https://drive.google.com/file/d/1-CyFQmIrezEuVPqOFgCXLaxm5raEtmYK/view?usp=sharing",
    },
    {
        id: 4,
        title: "API Design and Fundamentals of Google Cloud’s Apigee API Platform.",
        place: "Coursera",
        file_name: "apigee_design",
        url: "https://drive.google.com/file/d/18FrkITLl4Gug9pd4w9dzW6Uq2_n2P-qW/view?usp=sharing",
    },
    {
        id: 5,
        title: "API Security on Google Cloud’s Apigee API Platform.",
        place: "Coursera",
        file_name: "apigee_security",
        url: "https://drive.google.com/file/d/1Kr_4Vmi83CUT_I9Cb9PxURPB0aB1bHXM/view?usp=sharing",
    },
    {
        id: 6,
        title: "API Development on Google Cloud’s Apigee API Platform.",
        place: "Coursera",
        file_name: "apigee_dev",
        url: "https://drive.google.com/file/d/11q_qAnYXwXdv2XU1Mr3nC-Qq_pTVc4RY/view?usp=sharing",
    },
    {
        id: 7,
        title: "ROS (Robot Operating System) summer school from FH Aachen",
        place: "Aachen, Germany",
        file_name: "ROS_Certificate",
        url: "https://drive.google.com/file/d/1k2UyG1NPKKSpvfxCBwkpMYG_x2TmiS1S/view",
    },
];